title: Renato LovrekoviÄ‡ # your name (or website title) here
logo: "/images/preuzmi.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Indie game developer
  <br><br>
  Contact me any time on <a href=renato.lovrekovic@gmail.com">my e-mail</a> or on the linkedin linked below
  <br><br>
  <a href=https://www.linkedin.com/in/renato-lovrekovi%C4%87/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
